# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '@dsclose'
email: dsclose@gmail.com
description: 'Linux, Programming, Chess & Go.'
meta_description: '@dsclose: Linux, Programming, Chess & Go.'
url: "http://dsclose.github.io" # the base hostname & protocol for your site
twitter_username: dsclose
github_username: dsclose
timezone: Europe/London

# Build settings
markdown: kramdown
encoding: utf-8

# Kasper settings
markdown: kramdown
name: '@dsclose'
logo: true
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-66932714-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'dsclose.github.io'
author:         '@dsclose'
